/*
 * Copyright (c) 2017, Derwent Ready @ Drentsoft
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice, this
 *    list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 *    this list of conditions and the following disclaimer in the documentation
 *    and/or other materials provided with the distribution.
 * 3. Neither the name of the copyright holder nor the names of its contributors 
 *    may be used to endorse or promote products derived from this software 
 *    without specific prior written permission. 
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 */
package com.drentsoft.cardresizer.ui;

import com.drentsoft.cardresizer.OutputDimension;
import com.drentsoft.cardresizer.job.ResizeJob;
import javax.swing.JOptionPane;

/**
 *
 * @author Derwent Ready @ Drentsoft
 */
public class OutputOverviewPanel extends javax.swing.JPanel {

    ResizeJob job;
    
    public OutputOverviewPanel() {
        initComponents();
    }
    
    /**
     * Creates new form OutputSettingsPanel
     * @param job
     */
    public OutputOverviewPanel( ResizeJob job ) {
        initComponents();
        setJob(job);
    }
    
    public final void setJob( ResizeJob job ) {
        this.job = job;
        if( job.outputDimensions.size() > 0 ) {
            for( OutputDimension dim : job.outputDimensions) {
                outputTabs.add( "Resolution " + (outputTabs.getTabCount() + 1), new OutputFormatPanel( dim ) );
                outputTabs.setSelectedIndex( outputTabs.getTabCount() - 1 );
            }
        } else {
            addResBtnActionPerformed(null);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addResBtn = new javax.swing.JButton();
        copyResBtn = new javax.swing.JButton();
        delResBtn = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        outputTabs = new javax.swing.JTabbedPane();

        addResBtn.setText("Add Resolution");
        addResBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addResBtnActionPerformed(evt);
            }
        });

        copyResBtn.setText("Copy Resolution");
        copyResBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                copyResBtnActionPerformed(evt);
            }
        });

        delResBtn.setText("Delete Resolution");
        delResBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delResBtnActionPerformed(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Output Settings"));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(outputTabs)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(outputTabs, javax.swing.GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(addResBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(copyResBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(delResBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addResBtn)
                    .addComponent(delResBtn)
                    .addComponent(copyResBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addResBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addResBtnActionPerformed
        OutputDimension dim = new OutputDimension();
        job.outputDimensions.add( dim );
        outputTabs.add( "Resolution " + (outputTabs.getTabCount() + 1), new OutputFormatPanel(  dim ) );
        outputTabs.setSelectedIndex( outputTabs.getTabCount() - 1 );
    }//GEN-LAST:event_addResBtnActionPerformed

    private void copyResBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_copyResBtnActionPerformed
        OutputDimension origDim = job.outputDimensions.get( outputTabs.getSelectedIndex() );
        OutputDimension newDim = new OutputDimension(origDim);
        job.outputDimensions.add( newDim );
        outputTabs.add( "Resolution " + (outputTabs.getTabCount() + 1), new OutputFormatPanel( newDim ) );
        outputTabs.setSelectedIndex( outputTabs.getTabCount() - 1 );
    }//GEN-LAST:event_copyResBtnActionPerformed

    private void delResBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delResBtnActionPerformed
        if( job.outputDimensions.size() > 1 ) {
            int rv = JOptionPane.showConfirmDialog(this, "Are you sure you want to delete resolution output module?", "Delete Resolution?", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE );
            if( rv == JOptionPane.OK_OPTION ) {
                job.outputDimensions.remove( outputTabs.getSelectedIndex() );
                outputTabs.remove( outputTabs.getSelectedIndex() );
            }
        }
    }//GEN-LAST:event_delResBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addResBtn;
    private javax.swing.JButton copyResBtn;
    private javax.swing.JButton delResBtn;
    private javax.swing.JPanel jPanel3;
    public javax.swing.JTabbedPane outputTabs;
    // End of variables declaration//GEN-END:variables
}
