/*
 * Copyright (c) 2017, Derwent Ready @ Drentsoft
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice, this
 *    list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 *    this list of conditions and the following disclaimer in the documentation
 *    and/or other materials provided with the distribution.
 * 3. Neither the name of the copyright holder nor the names of its contributors 
 *    may be used to endorse or promote products derived from this software 
 *    without specific prior written permission. 
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 */
package com.drentsoft.cardresizer.ui;

import javax.swing.JFileChooser;

/**
 *
 * @author Derwent Ready @ Drentsoft
 */
public class ProgramSettingsPanel extends javax.swing.JPanel {

    /**
     * Creates new form ProgramSettingsPnael
     */
    public ProgramSettingsPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loadPDFChk = new javax.swing.JCheckBox();
        loadImgChk = new javax.swing.JCheckBox();
        saveSettingsBtn = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();
        dirLbl = new javax.swing.JLabel();
        dirField = new javax.swing.JTextField();
        dirBtn = new javax.swing.JButton();
        profilesLbl = new javax.swing.JLabel();
        profilesTxt = new javax.swing.JTextField();
        profilesBrowseBtn = new javax.swing.JButton();

        loadPDFChk.setText("Load PDF Job");
        loadPDFChk.setToolTipText("");

        loadImgChk.setText("Load Image Job");

        saveSettingsBtn.setText("Save");

        cancelBtn.setText("Cancel");

        dirLbl.setLabelFor(dirField);
        dirLbl.setText("Default Directory:");

        dirField.setToolTipText("");

        dirBtn.setText("Browse");
        dirBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dirBtnActionPerformed(evt);
            }
        });

        profilesLbl.setLabelFor(profilesTxt);
        profilesLbl.setText("Profiles Directory:");
        profilesLbl.setToolTipText("Location of local ICC profiles");

        profilesBrowseBtn.setText("Browse");
        profilesBrowseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profilesBrowseBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(saveSettingsBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cancelBtn))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dirField)
                    .addComponent(dirBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(profilesTxt)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(loadPDFChk)
                            .addComponent(loadImgChk)
                            .addComponent(dirLbl)
                            .addComponent(profilesLbl))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(profilesBrowseBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(loadPDFChk)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(loadImgChk)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dirLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dirField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dirBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(profilesLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(profilesTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(profilesBrowseBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveSettingsBtn)
                    .addComponent(cancelBtn)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void dirBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dirBtnActionPerformed
        JFileChooser fc = GlobalPanel.fc;
        fc.setFileSelectionMode( JFileChooser.DIRECTORIES_ONLY );
        fc.setMultiSelectionEnabled(false);
        int rv = fc.showOpenDialog(this);
        if( rv == JFileChooser.APPROVE_OPTION ) {
            if( fc.getSelectedFile().exists() && fc.getSelectedFile().isDirectory() ) {
                dirField.setText( fc.getSelectedFile().getPath() );
            }
        }
    }//GEN-LAST:event_dirBtnActionPerformed

    private void profilesBrowseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profilesBrowseBtnActionPerformed
        JFileChooser fc = GlobalPanel.fc;
        fc.setFileSelectionMode( JFileChooser.DIRECTORIES_ONLY );
        fc.setMultiSelectionEnabled(false);
        int rv = fc.showOpenDialog(this);
        if( rv == JFileChooser.APPROVE_OPTION ) {
            if( fc.getSelectedFile().exists() && fc.getSelectedFile().isDirectory() ) {
                profilesTxt.setText( fc.getSelectedFile().getPath() );
            }
        }
    }//GEN-LAST:event_profilesBrowseBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton cancelBtn;
    public javax.swing.JButton dirBtn;
    public javax.swing.JTextField dirField;
    private javax.swing.JLabel dirLbl;
    public javax.swing.JCheckBox loadImgChk;
    public javax.swing.JCheckBox loadPDFChk;
    public javax.swing.JButton profilesBrowseBtn;
    private javax.swing.JLabel profilesLbl;
    public javax.swing.JTextField profilesTxt;
    public javax.swing.JButton saveSettingsBtn;
    // End of variables declaration//GEN-END:variables
}
